version: '3.8'
services:
  resai-ui:
    build: ./resai-ui
    environment:
      PRESIDIO_ANALYZER_HOSTNAME: "localhost"
      PRESIDIO_ANALYZER_PORT: "5002"
      PRESIDIO_ANALYZER_ENDPOINT: "analyze"
      PRESIDIO_ANONYMIZER_HOSTNAME: "localhost"
      PRESIDIO_ANONYMIZER_PORT: "5001"
      PRESIDIO_ANONYMIZER_ENDPOINT: "anonymize"
    ports:
      - "3000:3000"
    networks:
      - resai

  presidio_analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - "5002:3000"
    networks:
      - resai

  presidio_anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - "5001:3000"
    networks:
      - resai

networks:
  resai:
    driver: bridge