version: '3.8'
services:
  resai-ui:
    build: ./resai-ui
    environment:
      PRESIDIO_ANALYZER_HOSTNAME: "localhost"
      PRESIDIO_ANALYZER_PORT: "5002"
      PRESIDIO_ANALYZER_ENDPOINT: "analyze"
      PRESIDIO_ANONYMIZER_HOSTNAME: "localhost"
      PRESIDIO_ANONYMIZER_PORT: "5001"
      PRESIDIO_ANONYMIZER_ENDPOINT: "anonymize"
    ports:
      - "3000:3000"
    networks:
      - resai

  presidio_analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - "5002:3000"
    networks:
      - resai

  presidio_anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - "5001:3000"
    networks:
      - resai

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
    networks:
      - resai

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
      - PROD_CORS_ORIGIN=http://localhost:3000
      # Set INSTRUMENT_LLAMA_INDEX=false to disable instrumentation
      - INSTRUMENT_LLAMA_INDEX=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:8000/api/chat/healthcheck"]
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - resai

networks:
  resai:
    driver: bridge